name: saint_env
channels:
  - pytorch
  - rwest
  - vgauthier
  - conda-forge
  - defaults
  - ostrokach
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _py-xgboost-mutex
  - anyio
  - argh
  - argon2-cffi
  - async_generator
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - blas
  - bleach
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - click
  - configparser
  - cryptography
  - cudatoolkit
  - cycler
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - docker-pycreds
  - einops
  - entrypoints
  - expat
  - ffmpeg
  - fontconfig
  - freetype
  - gettext
  - gitdb
  - gitpython
  - glib
  - glib-tools
  - gmp
  - gnutls
  - gql
  - graphql-core
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - importlib-metadata
  - intel-openmp
  - ipdb
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - kiwisolver
  - lame
  - lcms2
  - ld_impl_linux-64
  - liac-arff
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libglib
  - libgomp
  - libiconv
  - libidn2
  - libpng
  - libprotobuf
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libunistring
  - libuuid
  - libuv
  - libwebp-base
  - libxcb
  - libxgboost
  - libxml2
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - nettle
  - ninja
  - notebook
  - numpy
  - numpy-base
  - nvidia-ml
  - olefile
  - openh264
  - openml
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pathtools
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prometheus_client
  - promise
  - prompt-toolkit
  - protobuf
  - psutil
  - pthread-stubs
  - ptyprocess
  - py-xgboost
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-wget
  - python_abi
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - readline
  - requests
  - requests-unixsocket
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - sentry-sdk
  - setuptools
  - shortuuid
  - sip
  - six
  - smmap
  - sniffio
  - sqlite
  - subprocess32
  - terminado
  - testpath
  - threadpoolctl
  - tk
  - torchvision
  - tornado
  - traitlets
  - typing_extensions
  - urllib3
  - wandb
  - watchdog
  - wcwidth
  - webencodings
  - websocket-client
  - wget
  - wheel
  - xgboost
  - xmltodict
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd